version: 2.1

# If you do not already have Pipelines enabled, you'll need to go to Project Settings -> Advanced Settings and turn it on.

orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.5

jobs:
  install-deps:
  build:
    docker:
      - image: cimg/ruby:2.7.2-node # the primary container, where your job's commands are run

    executor:
      ruby/default

    steps:
      - checkout
      - run:
          name: Run Bundler
          command: bundle
      - run:
          name: Run RSpec
          command: rspec
      # - ruby/bundle-install
      # - ruby/rspec
