version: 2.1

# Orbs go here

# If you do not already have Pipelines enabled, you'll need to go to Project Settings -> Advanced Settings and turn it on.

orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.5

jobs:
  build:
    docker:
      # - image: cimg/node:14.10.1
      - image: cimg/ruby:2.7.2-node # the primary container, where your job's commands are run

    # What does this executor do?
    executor:
      ruby/default

      # auth:
      #   username: mydockerhub-user
      #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - rspec-test
